### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lenlight** [OpenKJ/OpenKJ-SongShop#1]
The Song Shop works great.
Would like to request for a PREVIEW feature. 
This can be a PREVIEW button right before the Purchase button.
Preview will enable a user to preview a song before purchasing.
This is a feature that is availed by most /all sellers of downloadable Karaoke songs.

In the Song Shop API with the URL for the song, we can add a URL that points to the sample video, this will be used for PREVIEW.
When a user clicks on the Preview button, a pop up preview window can appear to play the sample video.

**Comment by ILightburn** [comment]
I actually looked into this.  With party tyme specifically.  Because OpenKJ
is open source, they were concerned about people modifying it to steal
their songs.  And I actually get their concerns, as unfortunate as that
is.  Since anyone can modify the code, theoretically it would be possible
to save out the streamable songs to an mp4 and then share it via any of the
piracy distribution methods.

**Comment by lenlight** [comment]
Thank you for the response.
The previews are usually for public viewing and are easily downloadable.
They serve as samples, that can easily be saved.

For Party tyme, they have also made it easy for someone to save the previews.
On the Party Tyme site, if you right click on the Preview button and select save as, it will save the mp4 file on your computer.
Anyone can easily save the preview videos directly as mp4.

**Comment by lenlight** [comment]
I don't see an issue with anyone saving one or all the Preview videos because they cannot do much with them as they are usually 30-40 sec samples. 

I had also requested for a STREAM SHOP feature on openKJ. To enable users to subscribe to Karaoke Streaming Packages. This would entail streaming full songs. For this, there is serious concern if users would be able to save the full songs.
For the Stream Shop, I fully understand and agree to the concerns.
